import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "sonner"
import { Providers } from "./providers"
import NavMenu from "@/components/navMenu"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<head>
				<link
					rel="stylesheet"
					href="https://use.typekit.net/zaw6nld.css"
				></link>
			</head>
			<html lang="en" suppressHydrationWarning>
				<body className={inter.className}>
					<Providers>
						{children}
						<Toaster />
						<NavMenu />
					</Providers>
				</body>
			</html>
		</>
	)
}
